<?php
$data = array (
  0 => 
  array (
    'cat_id' => '8',
    'cat_name' => '网站公告',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  1 => 
  array (
    'cat_id' => '9',
    'cat_name' => '首页文章',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  2 => 
  array (
    'cat_id' => '10',
    'cat_name' => '帮助中心',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '14',
    'cat_name' => '满屏文章',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  5 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  6 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '4',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '4',
    'cat_name' => '购物指南',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  8 => 
  array (
    'cat_id' => '5',
    'cat_name' => '支付方式',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  9 => 
  array (
    'cat_id' => '6',
    'cat_name' => '配送方式',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  10 => 
  array (
    'cat_id' => '7',
    'cat_name' => '售后服务',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '帮助中心1',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '帮助中心2',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '帮助中心3',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
);
?>